[character]
success_symbol = "[â¯](bold 28)" 

[time]
disabled = false
format = 'ğŸ•™ [\[$time\]]($style)'
time_format = "%T"
style = "bold 28"

[cmd_duration]
min_time = 100
show_milliseconds = true
#style = "bold 178"

[python]
style = "100"

[git_status]
style = "167"
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
up_to_date = "âœ“"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[git_branch]
symbol = "ğŸŒ± "
ignore_branches = ["master", "main"]

